[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "https://test.iitiimjobs.com/*"
  to = "https://bookbarry.youcanbook.me/:splat"
  status = 301
  force = true
